matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
 - eval "${MATRIX_EVAL}"
 - sudo add-apt-repository ppa:beineri/opt-qt571 -y
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase57-dev 
 - sudo apt-get install qt57-default qttools57-dev-tools

script:
 - qmake -v
 - qmake zec-qt-wallet.pro CONFIG+=release 
 - make
