language: cpp

compiler: clang

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-6.0
      - clang

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev 
 - sudo apt-get install qt5-default qttools5-dev-tools

script:
 - qmake zec-qt-wallet.pro CONFIG+=release platform=linux-clang
 - make
