matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
 - eval "${MATRIX_EVAL}"
 - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
 - sudo apt-get update -qq
 - sudo apt-get install qt59base qt59tools
 - source /opt/qt59/bin/qt59-env.sh

script:
 - qmake -v
 - g++ -v
 - qmake zec-qt-wallet.pro CONFIG+=release 
 - make
